apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: provider-certification
  namespace: provider-certification
spec:
  params:
    - name: cluster-name
      type: string
      description: The cluster being certified
    
  tasks:
    - name: provider-certification-all
      params:
        - name: cluster-name
          value: $(params.cluster-name)
      taskRef:
        kind: Task
        name: provider-certification-task
