apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  namespace: provider-certification
  name: provider-certification-pr
spec:
  params:
  - name: cluster-name
    value: ${CLUSTER_NAME}
  pipelineRef:
    name: provider-certification
