kind: Pod
apiVersion: v1
metadata:
  name: debug-pod
  namespace: provider-certification
spec:
  containers:
    - name: debug-pod-container
      image: registry.access.redhat.com/ubi9/ubi-init:latest
      resources:
        limits:
          cpu: 200m
          memory: 1000Mi
        requests:
          cpu: 200m
          memory: 1000Mi
      volumeMounts:
      - mountPath: "/tmp"
        name: provider-cert-mount
      command: [ "sleep", "1000000" ]
  volumes:
    - name: provider-cert-mount
      persistentVolumeClaim:
        claimName: ${PVC_NAME}  
