apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-pv
spec:
  capacity:
    storage: 2Gi
  accessModes: 
  - ReadWriteOnce
  storageClassName: "standard"
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/operator"
