bases:
  - pvc.yaml
  - debug-pod.yaml

patchesJson6902:
- path: patches/patch-pvc-storageclass.yaml
  target:
    group: ''
    kind: PersistentVolumeClaim
    name: provider-cert-pvc
    version: v1

- path: patches/patch-pvc-name.yaml
  target:
    group: ''
    kind: Pod
    name: debug-pod
    version: v1
