apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: provider-cert-pvc
  namespace: provider-certification
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ${STORAGE_CLASS}
